In [6]:
import gym
import gym_Snake
import time
import sys
from IPython.display import clear_output
import numpy as np

In [2]:
env = gym.make('Snake-v0', width=11, height=11, solid_border=True)
print(env.observation_space)
print(env.action_space)

Discrete(121)
Discrete(3)


In [3]:
env.render()

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 4. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 2. 2. 0. 1.]
 [1. 0. 0. 0. 0. 3. 2. 2. 2. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 2. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 2. 2. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
env.reset()
if True:
    for i in range(5):
        clear_output(wait=True)
        env.render()
        env.step(np.random.randint(3))
        time.sleep(2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 3. 0. 0. 0. 0. 4. 1.]
 [1. 0. 0. 0. 2. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 2. 2. 0. 2. 2. 0. 1.]
 [1. 0. 0. 0. 0. 2. 2. 2. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
