In [1]:
import gym
import gym_Snake
import time
import sys
from IPython.display import clear_output
import numpy as np

In [2]:
env = gym.make('Snake-v0', width=7, height=7, solid_border=True)
print(env.observation_space)
print(env.action_space)

Discrete(49)
Discrete(3)


In [3]:
env.render()

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 7. 3. 0. 1.]
 [1. 0. 0. 0. 0. 2. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[]


In [4]:
# env.reset()
# if True:
#     for i in range(5):
#         clear_output(wait=True)
#         env.render()
#         env.step(np.random.randint(3))
#         time.sleep(2)

In [ ]:
env.reset()
done = False
while not done:
#     clear_output(wait=True)
    env.render()
    act = input('0 continue, 1 right, 2 left')
    obs, reward, done, info = env.step(int(act))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 7. 3. 0. 1.]
 [1. 0. 0. 0. 0. 2. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[]
0 continue, 1 right, 2 left1
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 4. 0. 0. 1.]
 [1. 0. 0. 3. 0. 0. 1.]
 [1. 0. 0. 0. 0. 2. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[]
0 continue, 1 right, 2 left1
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 3. 5. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 2. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[]
0 continue, 1 right, 2 left0
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 3. 5. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 2. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[]
0 continue, 1 right, 2 left1
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 3. 1.]
 [1. 0. 0. 0. 0. 6. 1.]
 [1. 0. 0. 0. 0. 2. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[]
0 continue, 1 right, 2 l