In [4]:
import gym
import gym_Snake
import time
import sys
from IPython.display import clear_output
import numpy as np

In [9]:
env = gym.make('Snake-v0', shape='Shuriken', player='computer', width=10, height=10, solid_border=True)
print(env.observation_space)
print(env.action_space)
env.render()

Discrete(1024)
Discrete(3)


In [3]:
# env.render(mode='print')
# env.step(0)
# env.step(0)
# env.render(mode='print')

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 2 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 8 3 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 2 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 8 3 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [4]:
env = env.clone()

In [5]:
env.render(mode='print')

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 2 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 8 3 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [6]:
# env.reset(player='human')

#### AI play random

In [7]:
# env.reset(player='computer', shape='Normal', state_mode='states', width=8, height=8, solid_border=True)
# if True:
#     done = False
#     while not done:
#         env.render()
#         obs, reward, done, info = env.step(np.random.randint(3))
#         print(obs)
#         time.sleep(0.5)
#     time.sleep(2)
#     env.close()

#### Play with human input

In [8]:
# env.reset(reward_mode = 'extended')
# done = False
# env.render()
# while not done:
# #     clear_output(wait=True)
    
#     act = input('0 continue, 1 right, 2 left')
#     obs, reward, done, info = env.step(int(act))
#     print(obs)
# #     print(info['walls'])
# #     print(info['target_pos'])
#     print(reward)
#     env.render()
# env.close()

#### Play in human mode, with arrows

In [9]:
# myBoard = [[1, 1, 1, 1, 1, 1, 1],
#            [1, 0, 0, 0, 0, 0, 1],
#            [1, 0, 0, 1, 0, 0, 1],
#            [1, 0, 0, 1, 0, 0, 1],
#            [1, 0, 0, 0, 0, 1, 1],
#            [1, 0, 0, 0, 1, 1, 1],
#            [1, 1, 1, 1, 1, 1, 1]]

In [10]:
# env.reset(player='human', custom_board=myBoard)

In [11]:
env.reset(player='human', shape='Normal', state_mode='states')

bottom_left_point
top_right_point
bottom_right_point
top_right_point
bottom_right_point
bottom_left_point
bottom_left_point
top_right_point
bottom_left_point
top_right_point
top_left_point
top_right_point
top_left_point
bottom_right_point
top_left_point
bottom_right_point
top_left_point
bottom_right_point
top_left_point
bottom_left_point
top_left_point
bottom_left_point
bottom_left_point
bottom_right_point
bottom_right_point
bottom_right_point
top_right_point
top_right_point
top_right_point
top_right_point
top_left_point
top_left_point
top_left_point
top_left_point
top_left_point
bottom_left_point
bottom_left_point
bottom_left_point
bottom_right_point
bottom_left_point
top_right_point
bottom_right_point
bottom_left_point
top_right_point
bottom_right_point
bottom_left_point
bottom_left_point
top_right_point
bottom_right_point
bottom_left_point
top_right_point
bottom_right_point
top_left_point
bottom_left_point
top_right_point
bottom_right_point
top_left_point
bottom_left_point
top_right

881

In [12]:
# env.reset(player='human', shape='Shuriken', width=10, height=12, solid_border=False, state_mode='states', reward_mode='extended')